//users
const userActionTypes = {
  UPDATE_LOGIN_STATUS_BY_INDEX: "UPDATE_LOGIN_STATUS_BY_INDEX",
  UPDATE_USER_NAME: "UPDATE_USER_NAME",
  RESET_USERS: "RESET_USERS",
};

const taskActionTypes = {
  ADD_NEW_TASK: "ADD_NEW_TASK",
  UPDATE_DESC: "UPDATE_DESC",
  ADD_NEW_COMMENTS_TO_TASK: "ADD_NEW_COMMENTS_TO_TASK",
};

const statusActionTypes = {
  ADD_NEW_STATUS: "ADD_NEW_STATUS",
  ADD_NEW_TASK_TO_STATUS: "ADD_NEW_TASK_TO_STATUS",
  SWAP_STATUS: "SWAP_STATUS",
  SWAP_TASKS_IN_SAME_STATUS: "SWAP_TASKS_IN_SAME_STATUS",
  ADD_TASKS_IN_DIFFERENT_STATUS: "ADD_TASKS_IN_DIFFERENT_STATUS",
};

const commentsActionTypes = {
  ADD_NEW_COMMENTS: "ADD_NEW_COMMENTS",
};

export default {
  ...userActionTypes,
  ...taskActionTypes,
  ...statusActionTypes,
  ...commentsActionTypes,
};
